# Generated by Django 2.2.4 on 2019-08-15 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.IntegerField(choices=[(1, '修缮'), (2, '加固危险点'), (3, '建议重建'), (4, '重建，停止使用，马上搬出'), (5, '取消鉴定')], verbose_name='处理意见')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '处理意见',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='城市')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '城市',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='FenceDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.IntegerField(choices=[(1, '未发现围护缺损'), (2, '同上'), (3, '墙体存在裂缝'), (4, '屋面坍塌'), (5, '屋面下陷'), (6, '墙体面层脱落'), (7, '墙体裂缝'), (8, '室内地面下陷'), (9, '内隔墙裂缝'), (10, '纵横墙多处裂缝')], verbose_name='描述')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '围护结构描述',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='GroundsillDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.IntegerField(choices=[(1, '未发现明显不均匀沉降及滑移'), (2, '地基基础轻微不均匀沉降'), (3, '地基基础不均匀沉降'), (4, '室内地面下陷'), (5, '地基基础滑移'), (6, '地基基础存在滑移可能'), (7, '地基基础被冲毁'), (8, '毛石基础粘结砂浆缺失')], verbose_name='描述')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '地基基础描述',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='审核人')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '审核人',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='SecurityDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.IntegerField(choices=[(1, '未发现影响房屋周边安全的不利影响'), (2, '房屋周边准在超高土体滑坡'), (3, '房屋周边场地存在地质斜坡'), (4, '房屋周边存在河流，受河水持续冲刷'), (5, '房屋存在沟壑'), (6, '房屋周边塌方'), (7, '房屋周边下方存在不实空洞')], verbose_name='描述')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '场地安全程度描述',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='TiltDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.IntegerField(choices=[(1, '未发现明显倾斜'), (2, '房屋墙体局部倾斜'), (3, '房屋墙体整体倾斜'), (4, '房屋墙体变形'), (5, '房屋墙体未发现明显歪闪缺陷')], verbose_name='描述')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '房屋整体倾斜描述',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='乡镇')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '乡镇',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UponDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.IntegerField(choices=[(1, '未发现结构承载缺陷'), (2, '墙体存在裂缝'), (3, '墙体轻微裂缝'), (4, '墙体贯通缝严重'), (5, '墙体风化侵蚀严重'), (6, '墙体有效截面积削弱'), (7, '内隔墙裂缝'), (8, '墙体面层脱落'), (9, '墙体变形'), (10, '墙体倾斜'), (11, '纵横墙连接处松动和开裂'), (12, '墙体倒塌'), (13, '屋架梁损坏'), (14, '屋架檩条损坏'), (15, '屋架梁下墙体开裂损坏'), (16, '屋架梁下墙体变形'), (17, '地基基础不均匀沉降引起的裂缝'), (18, '房屋墙体、屋盖无明显受力裂缝和变形'), (19, '墙体严重破坏，无法正常使用'), (20, '屋架损坏')], verbose_name='描述')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '房上部承重结构描述',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='村')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '村',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.CharField(blank=True, max_length=100, null=True, verbose_name='建鉴编号')),
                ('name', models.CharField(max_length=250, verbose_name='姓名')),
                ('identity', models.CharField(max_length=50, unique=True, verbose_name='身份证号')),
                ('decade', models.CharField(choices=[('0000', '未知'), ('1900', '1900'), ('1910', '1910'), ('1920', '1920'), ('1930', '1930'), ('1940', '1940'), ('1950', '1950'), ('1960', '1960'), ('1970', '1970'), ('1980', '1980'), ('1990', '1990'), ('2000', '2000'), ('2010', '2010')], default='0000', max_length=10, verbose_name='建成年代')),
                ('purpose', models.IntegerField(choices=[(1, '住宅'), (2, '厂房'), (3, '公共建筑')], default=1, verbose_name='用途')),
                ('comment', models.TextField(max_length=250, verbose_name='备注')),
                ('structure', models.IntegerField(choices=[(1, '混凝土结构'), (2, '砌体结构'), (3, '木结构'), (4, '钢结构'), (5, '石结构'), (6, '生土结构')], default=1, verbose_name='结构形式')),
                ('security', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default='a', max_length=10, verbose_name='场地安全程度')),
                ('groundsill', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default='a', max_length=10, verbose_name='地基基础')),
                ('tilt', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default='a', max_length=10, verbose_name='房屋整体倾斜')),
                ('upon', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default='a', max_length=10, verbose_name='上部承重结构')),
                ('fence', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default='a', max_length=10, verbose_name='围护结构')),
                ('assess_level', models.CharField(choices=[('a', 'A 完好无损'), ('b', 'B 轻微破损，可以使用'), ('c', 'C 破损经修缮后可以使用'), ('d', 'D 严重破坏，不能使用'), ('e', '倒塌')], default='a', max_length=10, verbose_name='评定等级')),
                ('street_contract', models.CharField(max_length=50, verbose_name='镇（街道）联系人')),
                ('street_contract_phone', models.CharField(max_length=50, verbose_name='镇（街道）联系人电话')),
                ('village_contract', models.CharField(max_length=50, verbose_name='村联系人')),
                ('village_contract_phone', models.CharField(max_length=50, verbose_name='村联系人电话')),
                ('created', models.DateField(auto_now_add=True, verbose_name='添加日期')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('advice', models.ManyToManyField(to='report.Advice', verbose_name='处理建议')),
                ('appraiser', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='鉴定人')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='report.City', verbose_name='城市')),
                ('fence_detail', models.ManyToManyField(to='report.FenceDetail', verbose_name='围护结构说明')),
                ('groundsill_detail', models.ManyToManyField(to='report.GroundsillDetail', verbose_name='地基基础说明')),
                ('reviewer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='report.Reviewer', verbose_name='审核人')),
                ('security_detail', models.ManyToManyField(to='report.SecurityDetail', verbose_name='场地安全程度说明')),
                ('tilt_detail', models.ManyToManyField(to='report.TiltDetail', verbose_name='房屋整体倾斜说明')),
                ('town', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='report.Town', verbose_name='镇')),
                ('upon_detail', models.ManyToManyField(to='report.UponDetail', verbose_name='上部承重结构说明')),
                ('village', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='report.Village', verbose_name='村')),
            ],
            options={
                'verbose_name_plural': '报告',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='%Y%m%d')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='添加日期')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='report_pics', to='report.Report')),
            ],
            options={
                'verbose_name_plural': '图片',
                'ordering': ('-created',),
            },
        ),
    ]
