# Generated by Django 2.2.4 on 2019-08-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20190816_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='advice',
            field=models.IntegerField(choices=[(0, ''), (1, '修缮'), (2, '加固危险点'), (3, '建议重建'), (4, '重建，停止使用，马上搬出'), (5, '取消鉴定')], verbose_name='处理意见'),
        ),
        migrations.AlterField(
            model_name='fencedetail',
            name='detail',
            field=models.IntegerField(choices=[(0, ''), (1, '未发现围护缺损'), (2, '同上'), (3, '墙体存在裂缝'), (4, '屋面坍塌'), (5, '屋面下陷'), (6, '墙体面层脱落'), (7, '墙体裂缝'), (8, '室内地面下陷'), (9, '内隔墙裂缝'), (10, '纵横墙多处裂缝')], verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='groundsilldetail',
            name='detail',
            field=models.IntegerField(choices=[(0, ''), (1, '未发现明显不均匀沉降及滑移'), (2, '地基基础轻微不均匀沉降'), (3, '地基基础不均匀沉降'), (4, '室内地面下陷'), (5, '地基基础滑移'), (6, '地基基础存在滑移可能'), (7, '地基基础被冲毁'), (8, '毛石基础粘结砂浆缺失')], verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='report',
            name='advice',
            field=models.ManyToManyField(to='report.Advice', verbose_name='处理建议'),
        ),
        migrations.AlterField(
            model_name='report',
            name='fence_detail',
            field=models.ManyToManyField(to='report.FenceDetail', verbose_name='围护结构说明'),
        ),
        migrations.AlterField(
            model_name='report',
            name='groundsill_detail',
            field=models.ManyToManyField(to='report.GroundsillDetail', verbose_name='地基基础说明'),
        ),
        migrations.AlterField(
            model_name='report',
            name='security_detail',
            field=models.ManyToManyField(to='report.SecurityDetail', verbose_name='场地安全程度说明'),
        ),
        migrations.AlterField(
            model_name='report',
            name='tilt_detail',
            field=models.ManyToManyField(to='report.TiltDetail', verbose_name='房屋整体倾斜说明'),
        ),
        migrations.AlterField(
            model_name='report',
            name='upon_detail',
            field=models.ManyToManyField(to='report.UponDetail', verbose_name='上部承重结构说明'),
        ),
        migrations.AlterField(
            model_name='securitydetail',
            name='detail',
            field=models.IntegerField(choices=[(0, ''), (1, '未发现影响房屋周边安全的不利影响'), (2, '房屋周边准在超高土体滑坡'), (3, '房屋周边场地存在地质斜坡'), (4, '房屋周边存在河流，受河水持续冲刷'), (5, '房屋存在沟壑'), (6, '房屋周边塌方'), (7, '房屋周边下方存在不实空洞')], verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='tiltdetail',
            name='detail',
            field=models.IntegerField(choices=[(0, ''), (1, '未发现明显倾斜'), (2, '房屋墙体局部倾斜'), (3, '房屋墙体整体倾斜'), (4, '房屋墙体变形'), (5, '房屋墙体未发现明显歪闪缺陷')], verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='upondetail',
            name='detail',
            field=models.IntegerField(choices=[(0, ''), (1, '未发现结构承载缺陷'), (2, '墙体存在裂缝'), (3, '墙体轻微裂缝'), (4, '墙体贯通缝严重'), (5, '墙体风化侵蚀严重'), (6, '墙体有效截面积削弱'), (7, '内隔墙裂缝'), (8, '墙体面层脱落'), (9, '墙体变形'), (10, '墙体倾斜'), (11, '纵横墙连接处松动和开裂'), (12, '墙体倒塌'), (13, '屋架梁损坏'), (14, '屋架檩条损坏'), (15, '屋架梁下墙体开裂损坏'), (16, '屋架梁下墙体变形'), (17, '地基基础不均匀沉降引起的裂缝'), (18, '房屋墙体、屋盖无明显受力裂缝和变形'), (19, '墙体严重破坏，无法正常使用'), (20, '屋架损坏')], verbose_name='描述'),
        ),
    ]
