# Generated by Django 2.2.4 on 2019-08-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20190816_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='advice',
            field=models.ManyToManyField(blank=True, to='report.Advice', verbose_name='处理建议'),
        ),
        migrations.AlterField(
            model_name='report',
            name='fence_detail',
            field=models.ManyToManyField(blank=True, to='report.FenceDetail', verbose_name='围护结构说明'),
        ),
        migrations.AlterField(
            model_name='report',
            name='groundsill_detail',
            field=models.ManyToManyField(blank=True, to='report.GroundsillDetail', verbose_name='地基基础说明'),
        ),
        migrations.AlterField(
            model_name='report',
            name='security_detail',
            field=models.ManyToManyField(blank=True, to='report.SecurityDetail', verbose_name='场地安全程度说明'),
        ),
        migrations.AlterField(
            model_name='report',
            name='tilt_detail',
            field=models.ManyToManyField(blank=True, to='report.TiltDetail', verbose_name='房屋整体倾斜说明'),
        ),
        migrations.AlterField(
            model_name='report',
            name='upon_detail',
            field=models.ManyToManyField(blank=True, to='report.UponDetail', verbose_name='上部承重结构说明'),
        ),
    ]
