# Generated by Django 3.2.2 on 2021-05-11 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0008_auto_20190823_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='neighbor_east',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='东邻'),
        ),
        migrations.AddField(
            model_name='report',
            name='neighbor_north',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='北邻'),
        ),
        migrations.AddField(
            model_name='report',
            name='neighbor_south',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='南邻'),
        ),
        migrations.AddField(
            model_name='report',
            name='neighbor_west',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='西邻'),
        ),
    ]
