# Generated by Django 3.2.2 on 2021-05-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_alter_report_room_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='room_num',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='房间数量'),
        ),
    ]
